### ISSUE TITLE
Server Render问题

### ISSUE THREAD

**Issue by willin** [luqin/react-router-loader#11]
hi，

我在用 `webpack` 打包的时候，是没有问题的。

但是 server端 有这么一段

```
import { match, RouterContext } from 'react-router';
import routes from '../app/modules/routes'; // 加载路由
```

就会报错

```
Error: Cannot find module 'react-router?name=default!./modules/App'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/willin/Documents/others/test/.dev/app/index.js:18:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

该怎么解决呢

**Comment by luqin** [comment]
@willin 
暂时还没测试过同构渲染，这是运行时错误码？

**Comment by willin** [comment]
是的，babel抛出的

**Comment by willin** [comment]
还有一个问题

用了 `require('react-router!xxxxx')`引用的router里面内容不能热加载。

```
webpack-dev-server --config webpack.config.dev.js --colors --devtool eval --hot --inline --no-info --content-base static/react --history-api-fallback
```

**Comment by luqin** [comment]
谢谢反馈

**Comment by luqin** [comment]
经过测试，是支持热加载的
